// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WashingCar.DAL;

#nullable disable

namespace WashingCar.Migrations
{
    [DbContext(typeof(DatabaseContext))]
    [Migration("20230507174030_InitialDataBase")]
    partial class InitialDataBase
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("WashingCar.DAL.Entities.Service", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Price")
                        .HasColumnType("float");

                    b.Property<Guid?>("VehicleId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("VehicleId");

                    b.ToTable("Services");
                });

            modelBuilder.Entity("WashingCar.DAL.Entities.Vehicle", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("NumberPlate")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Owner")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("VehicleDetailId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("VehicleDetailId");

                    b.ToTable("Vehicles");
                });

            modelBuilder.Entity("WashingCar.DAL.Entities.VehicleDetail", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("CreationDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeliveryDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("vehicleDetails");
                });

            modelBuilder.Entity("WashingCar.DAL.Entities.Service", b =>
                {
                    b.HasOne("WashingCar.DAL.Entities.Vehicle", null)
                        .WithMany("Services")
                        .HasForeignKey("VehicleId");
                });

            modelBuilder.Entity("WashingCar.DAL.Entities.Vehicle", b =>
                {
                    b.HasOne("WashingCar.DAL.Entities.VehicleDetail", null)
                        .WithMany("Vehicles")
                        .HasForeignKey("VehicleDetailId");
                });

            modelBuilder.Entity("WashingCar.DAL.Entities.Vehicle", b =>
                {
                    b.Navigation("Services");
                });

            modelBuilder.Entity("WashingCar.DAL.Entities.VehicleDetail", b =>
                {
                    b.Navigation("Vehicles");
                });
#pragma warning restore 612, 618
        }
    }
}
